import { defineMiddleware } from 'astro:middleware';

/**
 * Host-scoped `X-Robots-Tag` for the three on-demand routes: /api/contact,
 * /api/ftp and /img/[...path]. Nothing else ever reaches this file.
 *
 * Every page on this site sets `prerender = true`, so it is served as a
 * static file straight out of the Workers assets binding and never touches
 * the Worker script -- Cloudflare's own docs are explicit that a `_headers`
 * rule is what protects those (see `public/_headers`), and that custom
 * headers defined there are "not applied to responses generated by your
 * Worker code" even when the URL matches
 * (developers.cloudflare.com/workers/static-assets/headers/). This
 * middleware is the other half of that same fix, scoped to the on-demand
 * routes `_headers` cannot see.
 *
 * Scoped to the literal `*.workers.dev` hostname -- not "anything that is
 * not production" -- for the same reason the `_headers` rule is: the
 * client's own boldeimaging.com must never match this, in this file or any
 * future one, so a refactor here can never quietly de-index the client's
 * live site.
 */
const WORKERS_DEV = /(^|\.)workers\.dev$/;

export const onRequest = defineMiddleware(async ({ url }, next) => {
  const response = await next();
  if (!WORKERS_DEV.test(url.hostname)) {
    return response;
  }

  // `response` can be a Cache API hit (e.g. the /img route's `cache.match`
  // fast path) or another already-sealed Response whose `headers` are
  // read-only; calling `.set` on those throws a TypeError and turns every
  // cached image into a 500 on *.workers.dev. Wrapping it constructs a
  // fresh, mutable Response with the same status/body/headers instead of
  // mutating the original in place. This is a plain pass-through wrapper --
  // it does not buffer the body -- so streaming and `Range`/206 responses
  // are forwarded unchanged.
  const mutable = new Response(response.body, response);
  mutable.headers.set('X-Robots-Tag', 'noindex, nofollow, noarchive');
  return mutable;
});
