import { defineMiddleware } from 'astro:middleware';

/**
 * Host-scoped `X-Robots-Tag` for the three on-demand routes: /api/contact,
 * /api/ftp and /img/[...path]. Nothing else ever reaches this file.
 *
 * Every page on this site sets `prerender = true`, so it is served as a
 * static file straight out of the Workers assets binding and never touches
 * the Worker script -- Cloudflare's own docs are explicit that a `_headers`
 * rule is what protects those (see `public/_headers`), and that custom
 * headers defined there are "not applied to responses generated by your
 * Worker code" even when the URL matches
 * (developers.cloudflare.com/workers/static-assets/headers/). This
 * middleware is the other half of that same fix, scoped to the on-demand
 * routes `_headers` cannot see.
 *
 * Scoped to the literal `*.workers.dev` hostname -- not "anything that is
 * not production" -- for the same reason the `_headers` rule is: the
 * client's own boldeimaging.com and the reviewed boldeimaging.10xid.com
 * staging host must never match this, in this file or any future one, so a
 * refactor here can never quietly de-index the client's live site.
 * boldeimaging.10xid.com already gets its own edge X-Robots-Tag from a
 * zone-level Transform Rule (see README, "The preview is noindexed") --
 * this middleware does not duplicate or depend on that.
 */
const WORKERS_DEV = /(^|\.)workers\.dev$/;

export const onRequest = defineMiddleware(async ({ url }, next) => {
  const response = await next();
  if (WORKERS_DEV.test(url.hostname)) {
    response.headers.set('X-Robots-Tag', 'noindex, nofollow, noarchive');
  }
  return response;
});
